name: monitoring_kambing
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  expansion_tile_group: ^1.2.4
  rounded_expansion_tile: ^0.0.13
  mrx_charts: ^0.1.3
  intl: ^0.19.0
  data_table_2: ^2.5.10
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.69.0
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/anggota/
    - assets/images/logo_keren.png
    - assets/images/sensor/RaFID.png
    - assets/images/sensor/loadcellBadan.png
    - assets/images/sensor/loadcellpakan.png
    - assets/images/sensor/aht.png
    - assets/images/sensor/mpu.png